### ISSUE TITLE
Problems when building on mingw32/mingw64/msys

### ISSUE THREAD

**Issue by vanklompf** [Juppit/esp-new-sdk#2]
Hi,

I have some problems building tool-chain on Windows.
Maybe you have suggestions what is wrong?

MSYS:
```
tmp-invert_limb_table.s: Assembler messages:
tmp-invert_limb_table.s:46: Error: unknown pseudo-op: `.hidden'
make[4]: *** [Makefile:768: invert_limb_table.lo] Error 1
make[3]: *** [Makefile:956: all-recursive] Error 1
make[2]: *** [Makefile:775: all] Error 2
make[1]: *** [Makefile:852: /c/Projekty/esp-new-sdk_msys/src/.gmp.builded] Error 2
````

MINGW64:
```
../../libiberty/pex-win32.c:943:35: error: ‘_O_BINARY’ undeclared (first use in this function)
   return _pipe (p, 256, (binary ? _O_BINARY : _O_TEXT) | _O_NOINHERIT);
                                   ^~~~~~~~~
../../libiberty/pex-win32.c:943:47: error: ‘_O_TEXT’ undeclared (first use in this function)
   return _pipe (p, 256, (binary ? _O_BINARY : _O_TEXT) | _O_NOINHERIT);
                                               ^~~~~~~
../../libiberty/pex-win32.c:943:58: error: ‘_O_NOINHERIT’ undeclared (first use in this function)
   return _pipe (p, 256, (binary ? _O_BINARY : _O_TEXT) | _O_NOINHERIT);
```

MINGW32 (but it's not on supported list in readme.md, so probably it's ok)
```
configure: error: could not find a working compiler, see config.log for details
make[1]: *** [Makefile:850: /c/Projekty/esp-new-sdk_mingw32/src/.gmp.configured] Error 1 
```

**Comment by Juppit** [comment]
Have a look in /c/Projekty/esp-new-sdk/distrib there will be xxx-error.log with a bit more infos.
In the makefile you find this on line 176:
```
SAFEPATH = "$(TOOLCHAIN)/bin:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
```
Maybe this is not what your path is in MSYS, MINGW64 or MINGW32.

**Comment by vanklompf** [comment]
Outputs above are from ```xxx-error.log```
It doesn't seem to be related with paths.

I have created AppVeyor setup:
https://ci.appveyor.com/project/vanklompf/esp-new-sdk
And errors there are exactly the same as on my PC.
I can create PR with AppVeyor config, if You want to have it as part of Continous Integration along Travis.

For MSYS I think error is related to this problem (.hidden should be used for ELF only):
https://www.mail-archive.com/gmp-bugs@gmplib.org/msg00194.html
But I don't know how to fix that.

MINGW64 progresses much further but it also fails. You can see full error log on AppVeyor build.

**Comment by Juppit** [comment]
Of course a PR with a config for AppVeyor would be fine.

After the make stopped on Mingw64 try the following steps in the appropriate directories:
rm -R esp-new-sdk/src/binutils-2.29.1/build-MINGW64*
make -C esp-new-sdk/src/binutils-2.29.1/build-MINGW64_NT-10.0
So you will see the full output of make.
Or you change the variable QUIET in makefile at line 340 to an empty string like
' QUIET :='
and then you can call
make build-binutils
with less output, but all errors.

Or you try a different binutils like 2.26, simply uncomment the lines 143 to 146,
then call 'make build-binutils'.

ATM I do not find time to set up an MINGW system and try it myself.

**Comment by vanklompf** [comment]
Thanks.
I will try to investigate that.

**Comment by Juppit** [comment]
Meanwhile I build the project with MinGW64.
I've adjusted the path so gcc will be found. The path starts now with
> /mingw64/bin:
This works for me.

**Comment by Juppit** [comment]
You should use the new Makefile, because the path is there overwritten.

**Comment by vanklompf** [comment]
Thank you for help.
I was able to build it locally using Mingw64. I still have some problems building it on AppVeyor, but I will work on fixing that.
